pagina = input("Nombre pagina: ")
pagina = pagina+".html"
color = input("En que color: ")
ent = open(pagina,"w")
ent.write("<html>"+"\n")
ent.write("    <body bgcolor="+"'"+color+"'"+">"+"\n")
ent.write("      <h1>"+"\n")
ent.write("         Hola Mundo!!!"+"\n")
ent.write("        </h1>"+"\n")
ent.write("        <hr>"+"\n")
ent.write("      <h2>"+"\n")
ent.write("           Hugo Araya Carrasco"+"\n")
ent.write("       </h2>"+"\n")
ent.write("    </body>"+"\n")
ent.write("</html>"+"\n")
ent.close()